"""Pre-compiled protobuf stubs for the Rachio mobile gRPC API.

Generated by scripts/build_protos.sh from reverse-engineering/protos/.
Do not edit by hand; changes will be overwritten on the next regen.

The generated modules use bare imports of the form `import foo_pb2` which
assume this directory is on sys.path. rachio_mcp.client adds it at import
time so consumers don't need to do anything.
"""
