# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aggregation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aggregation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import core_pb2 as core__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61ggregation.proto\x1a\ncore.proto\"}\n\x13\x41ggregationCriteria\x12&\n\ntime_frame\x18\x01 \x01(\x0b\x32\x12.TimestampInterval\x12\x1b\n\x08interval\x18\x02 \x01(\x0e\x32\t.Interval\x12!\n\x0b\x61ggregation\x18\x03 \x01(\x0e\x32\x0c.Aggregation\"Q\n\tAggregate\x12&\n\ntime_frame\x18\x01 \x01(\x0b\x32\x12.TimestampInterval\x12\r\n\x05value\x18\x02 \x01(\x01\x12\r\n\x05group\x18\x03 \x01(\t*H\n\x08Interval\x12\n\n\x06MINUTE\x10\x00\x12\x08\n\x04HOUR\x10\x01\x12\x07\n\x03\x44\x41Y\x10\x02\x12\x08\n\x04WEEK\x10\x03\x12\t\n\x05MONTH\x10\x04\x12\x08\n\x04YEAR\x10\x05*H\n\x0b\x41ggregation\x12\x07\n\x03SUM\x10\x00\x12\x0b\n\x07\x41VERAGE\x10\x01\x12\t\n\x05\x43OUNT\x10\x02\x12\x0b\n\x07MINIMUM\x10\x03\x12\x0b\n\x07MAXIMUM\x10\x04\x42\x19\n\x15\x63om.rachio.api.metricP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aggregation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.rachio.api.metricP\001'
  _globals['_INTERVAL']._serialized_start=243
  _globals['_INTERVAL']._serialized_end=315
  _globals['_AGGREGATION']._serialized_start=317
  _globals['_AGGREGATION']._serialized_end=389
  _globals['_AGGREGATIONCRITERIA']._serialized_start=33
  _globals['_AGGREGATIONCRITERIA']._serialized_end=158
  _globals['_AGGREGATE']._serialized_start=160
  _globals['_AGGREGATE']._serialized_end=241
# @@protoc_insertion_point(module_scope)
