# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: alert.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'alert.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61lert.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x98\x02\n\x05\x41lert\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tentity_id\x18\x02 \x01(\t\x12\x18\n\x04type\x18\x03 \x01(\x0e\x32\n.AlertType\x12\r\n\x05title\x18\x04 \x01(\t\x12\x10\n\x08subtitle\x18\x05 \x01(\t\x12\x0f\n\x07summary\x18\x06 \x01(\t\x12\x11\n\tdismissed\x18\x07 \x01(\x08\x12\x37\n\x13\x64ismissed_timestamp\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07\x63reated\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07updated\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestamp*\x9c\x01\n\tAlertType\x12\x12\n\x0eZONE_HIGH_FLOW\x10\x00\x12\x11\n\rZONE_LOW_FLOW\x10\x01\x12\x1d\n\x19ZONE_HIGH_FLOW_NO_SHUTOFF\x10\x02\x12\x1a\n\x16ZONE_HIGH_FLOW_SHUTOFF\x10\x03\x12\x15\n\x11ZONE_LOW_AMPERAGE\x10\x04\x12\x16\n\x12ZONE_HIGH_AMPERAGE\x10\x05\x42\x19\n\x15\x63om.rachio.api.deviceP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'alert_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.rachio.api.deviceP\001'
  _globals['_ALERTTYPE']._serialized_start=364
  _globals['_ALERTTYPE']._serialized_end=520
  _globals['_ALERT']._serialized_start=81
  _globals['_ALERT']._serialized_end=361
# @@protoc_insertion_point(module_scope)
