# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth_extension.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "auth_extension.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n\x14\x61uth_extension.proto\x1a google/protobuf/descriptor.proto*\x93\x01\n\x08\x41uthRole\x12\x08\n\x04NONE\x10\x00\x12\x10\n\x0cMANUFACTURER\x10\x01\x12\t\n\x05\x41\x44MIN\x10\x02\x12\x0e\n\nMUNI_ADMIN\x10\x03\x12\x08\n\x04USER\x10\x04\x12\x07\n\x03PRO\x10\x05\x12\r\n\tPRO_ADMIN\x10\x06\x12\x10\n\x0cPORTAL_ADMIN\x10\x07\x12\x0f\n\x0bPORTAL_USER\x10\x08\x12\x0b\n\x07\x41UDITOR\x10\tB\x12\n\x0e\x63om.rachio.apiP\x01\x62\x06proto3"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "auth_extension_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"\n\016com.rachio.apiP\001"
    _globals["_AUTHROLE"]._serialized_start = 59
    _globals["_AUTHROLE"]._serialized_end = 206
# @@protoc_insertion_point(module_scope)
