# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "device.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0c\x64\x65vice.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\ncore.proto"\xca\x01\n\x06\x44\x65vice\x12\n\n\x02id\x18\x01 \x01(\t\x12\x19\n\x04type\x18\x02 \x01(\x0e\x32\x0b.DeviceType\x12+\n\x07\x63reated\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07updated\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\x1c\n\tgeo_point\x18\x07 \x01(\x0b\x32\t.GeoPoint\x12\x13\n\x0blocation_id\x18\x08 \x01(\t*\xd8\x01\n\nDeviceType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x13\n\x0f\x43ONTROLLER_GEN1\x10\x01\x12\x13\n\x0f\x43ONTROLLER_GEN2\x10\x02\x12\x11\n\rSENSOR_LINKED\x10\x03\x12\x1c\n\x18WEATHER_STATION_PHYSICAL\x10\x04\x12\x1b\n\x17WEATHER_STATION_VIRTUAL\x10\x05\x12\x13\n\x0f\x43ONTROLLER_GEN3\x10\x06\x12\x18\n\x14WIRELESS_FLOW_SENSOR\x10\x07\x12\x16\n\x12\x43ONTROLLER_VIRTUAL\x10\x08*,\n\x0eWiringPosition\x12\x0c\n\x08SLOT_ONE\x10\x00\x12\x0c\n\x08SLOT_TWO\x10\x01\x42\x19\n\x15\x63om.rachio.api.deviceP\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "device_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"\n\025com.rachio.api.deviceP\001"
    _globals["_DEVICETYPE"]._serialized_start = 267
    _globals["_DEVICETYPE"]._serialized_end = 483
    _globals["_WIRINGPOSITION"]._serialized_start = 485
    _globals["_WIRINGPOSITION"]._serialized_end = 529
    _globals["_DEVICE"]._serialized_start = 62
    _globals["_DEVICE"]._serialized_end = 264
# @@protoc_insertion_point(module_scope)
