# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flow_provision_get.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "flow_provision_get.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x18\x66low_provision_get.proto\x1a\x1a\x66low_provision_model.proto\x1a\x1egoogle/protobuf/wrappers.proto"0\n\x17GetFlowProvisionRequest\x12\x15\n\rserial_number\x18\x01 \x01(\t"=\n\x18GetFlowProvisionResponse\x12!\n\tprovision\x18\x01 \x01(\x0b\x32\x0e.FlowProvision"6\n\x1dGetFlowProvisionBinaryRequest\x12\x15\n\rserial_number\x18\x01 \x01(\t"W\n\x1eGetFlowProvisionBinaryResponse\x12\x35\n\x10mfg_config_bytes\x18\x01 \x01(\x0b\x32\x1b.google.protobuf.BytesValue"\x1c\n\x1a\x41ssignFlowProvisionRequest"@\n\x1b\x41ssignFlowProvisionResponse\x12!\n\tprovision\x18\x01 \x01(\x0b\x32\x0e.FlowProvisionB \n\x1c\x63om.rachio.api.flowprovisionP\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "flow_provision_get_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b"\n\034com.rachio.api.flowprovisionP\001"
    _globals["_GETFLOWPROVISIONREQUEST"]._serialized_start = 88
    _globals["_GETFLOWPROVISIONREQUEST"]._serialized_end = 136
    _globals["_GETFLOWPROVISIONRESPONSE"]._serialized_start = 138
    _globals["_GETFLOWPROVISIONRESPONSE"]._serialized_end = 199
    _globals["_GETFLOWPROVISIONBINARYREQUEST"]._serialized_start = 201
    _globals["_GETFLOWPROVISIONBINARYREQUEST"]._serialized_end = 255
    _globals["_GETFLOWPROVISIONBINARYRESPONSE"]._serialized_start = 257
    _globals["_GETFLOWPROVISIONBINARYRESPONSE"]._serialized_end = 344
    _globals["_ASSIGNFLOWPROVISIONREQUEST"]._serialized_start = 346
    _globals["_ASSIGNFLOWPROVISIONREQUEST"]._serialized_end = 374
    _globals["_ASSIGNFLOWPROVISIONRESPONSE"]._serialized_start = 376
    _globals["_ASSIGNFLOWPROVISIONRESPONSE"]._serialized_end = 440
# @@protoc_insertion_point(module_scope)
