# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flow_provision_model.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "flow_provision_model.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n\x1a\x66low_provision_model.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0fprovision.proto\"\xc4\x05\n\rFlowProvision\x12\x15\n\rserial_number\x18\x01 \x01(\t\x12\x0b\n\x03pin\x18\x02 \x01(\t\x12\x13\n\x0bmac_address\x18\x03 \x01(\t\x12\x0b\n\x03key\x18\x04 \x01(\t\x12\x18\n\x10\x66irmware_version\x18\x05 \x01(\t\x12\x19\n\x05model\x18\x06 \x01(\x0e\x32\n.FlowModel\x12 \n\x06status\x18\x07 \x01(\x0e\x32\x10.ProvisionStatus\x12'\n\x10pcb_manufacturer\x18\x08 \x01(\x0e\x32\r.Manufacturer\x12&\n\x0e\x66inal_assembly\x18\t \x01(\x0e\x32\x0e.FinalAssembly\x12\x0c\n\x04type\x18\n \x01(\x05\x12\x0f\n\x07profile\x18\x0b \x01(\x05\x12\x14\n\x0cpreamble_len\x18\x0c \x01(\x05\x12\x10\n\x08interval\x18\r \x01(\x05\x12\x1e\n\x16resp_interval_num_wake\x18\x0e \x01(\x05\x12\x12\n\nuse_ch_num\x18\x0f \x01(\x08\x12\x14\n\x0c\x65\x63pt_cnt_max\x18\x10 \x01(\x05\x12\x13\n\x0b\x63rc_cnt_max\x18\x11 \x01(\x05\x12\x14\n\x0cwake_cnt_max\x18\x12 \x01(\x05\x12\x13\n\x0bhb_interval\x18\x13 \x01(\x05\x12\x12\n\nhb_timeout\x18\x14 \x01(\x05\x12\x17\n\x0fstatus_interval\x18\x15 \x01(\x05\x12:\n\x16pcb_manufacturing_time\x18\x16 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\rassembly_time\x18\x17 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07\x63reated\x18\x18 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07updated\x18\x19 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*\x1d\n\rFinalAssembly\x12\x0c\n\x08\x46LOW_PRO\x10\x00*\x18\n\tFlowModel\x12\x0b\n\x07\x46LOW_V1\x10\x00\x42 \n\x1c\x63om.rachio.api.flowprovisionP\x01\x62\x06proto3"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "flow_provision_model_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b"\n\034com.rachio.api.flowprovisionP\001"
    _globals["_FINALASSEMBLY"]._serialized_start = 791
    _globals["_FINALASSEMBLY"]._serialized_end = 820
    _globals["_FLOWMODEL"]._serialized_start = 822
    _globals["_FLOWMODEL"]._serialized_end = 846
    _globals["_FLOWPROVISION"]._serialized_start = 81
    _globals["_FLOWPROVISION"]._serialized_end = 789
# @@protoc_insertion_point(module_scope)
