# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: location_summary.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "location_summary.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x16location_summary.proto\x1a\x0elocation.proto\x1a\x14location_state.proto\x1a\nuser.proto\x1a\x0b\x61lert.proto"\xe3\x01\n\x0fLocationSummary\x12\x1b\n\x08location\x18\x01 \x01(\x0b\x32\t.Location\x12\x1d\n\x05state\x18\x02 \x01(\x0b\x32\x0e.LocationState\x12\x14\n\x05owner\x18\x03 \x01(\x0b\x32\x05.User\x12\x10\n\x08\x66\x61vorite\x18\x04 \x01(\x08\x12\x14\n\x0chas_messages\x18\x05 \x01(\x08\x12\x16\n\x0etier_one_count\x18\x06 \x01(\x05\x12\x16\n\x0etier_two_count\x18\x07 \x01(\x05\x12&\n\x12\x61\x63tive_alert_types\x18\x08 \x03(\x0e\x32\n.AlertTypeB\x1b\n\x17\x63om.rachio.api.locationP\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "location_summary_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"\n\027com.rachio.api.locationP\001"
    _globals["_LOCATIONSUMMARY"]._serialized_start = 90
    _globals["_LOCATIONSUMMARY"]._serialized_end = 317
# @@protoc_insertion_point(module_scope)
