# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: location_state.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'location_state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14location_state.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xed\x03\n\rLocationState\x12\x13\n\x0blocation_id\x18\x01 \x01(\t\x12%\n\x06health\x18\x02 \x01(\x0e\x32\x15.LocationState.Health\x12#\n\x05state\x18\x03 \x01(\x0e\x32\x14.LocationState.State\x12,\n\x08last_run\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08next_run\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x14\n\x0cusage_liters\x18\x06 \x01(\x01\x12\"\n\x1alocal_average_usage_liters\x18\x07 \x01(\x01\x12\x18\n\x10\x66irmware_version\x18\x08 \x01(\t\"\x9e\x01\n\x05State\x12\x0b\n\x07STANDBY\x10\x00\x12\x08\n\x04IDLE\x10\x01\x12\t\n\x05\x44\x45LAY\x10\x02\x12\n\n\x06PAUSED\x10\x03\x12\x0c\n\x08WATERING\x10\x04\x12\x0b\n\x07UNKNOWN\x10\x05\x12\n\n\x06UNBORN\x10\x06\x12\x0b\n\x07STARTUP\x10\x07\x12\x0b\n\x07OFFLINE\x10\x08\x12\x14\n\x10\x45XTENDED_OFFLINE\x10\t\x12\x10\n\x0cPROVISIONING\x10\n\"*\n\x06Health\x12\x08\n\x04GOOD\x10\x00\x12\x0b\n\x07WARNING\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x42\x1b\n\x17\x63om.rachio.api.locationP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'location_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027com.rachio.api.locationP\001'
  _globals['_LOCATIONSTATE']._serialized_start=58
  _globals['_LOCATIONSTATE']._serialized_end=551
  _globals['_LOCATIONSTATE_STATE']._serialized_start=349
  _globals['_LOCATIONSTATE_STATE']._serialized_end=507
  _globals['_LOCATIONSTATE_HEALTH']._serialized_start=509
  _globals['_LOCATIONSTATE_HEALTH']._serialized_end=551
# @@protoc_insertion_point(module_scope)
