# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import location_service_pb2 as location__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in location_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LocationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLocation = channel.unary_unary(
                '/LocationService/GetLocation',
                request_serializer=location__service__pb2.GetLocationRequest.SerializeToString,
                response_deserializer=location__service__pb2.GetLocationResponse.FromString,
                _registered_method=True)
        self.CreateLocation = channel.unary_unary(
                '/LocationService/CreateLocation',
                request_serializer=location__service__pb2.CreateLocationRequest.SerializeToString,
                response_deserializer=location__service__pb2.CreateLocationResponse.FromString,
                _registered_method=True)
        self.DeleteLocation = channel.unary_unary(
                '/LocationService/DeleteLocation',
                request_serializer=location__service__pb2.DeleteLocationRequest.SerializeToString,
                response_deserializer=location__service__pb2.DeleteLocationResponse.FromString,
                _registered_method=True)
        self.UpdateLocation = channel.unary_unary(
                '/LocationService/UpdateLocation',
                request_serializer=location__service__pb2.UpdateLocationRequest.SerializeToString,
                response_deserializer=location__service__pb2.UpdateLocationResponse.FromString,
                _registered_method=True)
        self.ListLocations = channel.unary_unary(
                '/LocationService/ListLocations',
                request_serializer=location__service__pb2.ListLocationsRequest.SerializeToString,
                response_deserializer=location__service__pb2.ListLocationsResponse.FromString,
                _registered_method=True)
        self.GetRestriction = channel.unary_unary(
                '/LocationService/GetRestriction',
                request_serializer=location__service__pb2.GetRestrictionRequest.SerializeToString,
                response_deserializer=location__service__pb2.GetRestrictionResponse.FromString,
                _registered_method=True)
        self.UpdateRestriction = channel.unary_unary(
                '/LocationService/UpdateRestriction',
                request_serializer=location__service__pb2.UpdateRestrictionRequest.SerializeToString,
                response_deserializer=location__service__pb2.UpdateRestrictionResponse.FromString,
                _registered_method=True)
        self.ClearRestriction = channel.unary_unary(
                '/LocationService/ClearRestriction',
                request_serializer=location__service__pb2.ClearRestrictionRequest.SerializeToString,
                response_deserializer=location__service__pb2.ClearRestrictionResponse.FromString,
                _registered_method=True)
        self.GetWeatherByLocation = channel.unary_unary(
                '/LocationService/GetWeatherByLocation',
                request_serializer=location__service__pb2.GetWeatherByLocationRequest.SerializeToString,
                response_deserializer=location__service__pb2.GetWeatherResponse.FromString,
                _registered_method=True)
        self.GetClosestWeatherStations = channel.unary_unary(
                '/LocationService/GetClosestWeatherStations',
                request_serializer=location__service__pb2.GetClosestWeatherStationsRequest.SerializeToString,
                response_deserializer=location__service__pb2.GetClosestWeatherStationsResponse.FromString,
                _registered_method=True)
        self.GetLocationPhoto = channel.unary_unary(
                '/LocationService/GetLocationPhoto',
                request_serializer=location__service__pb2.GetLocationPhotoRequest.SerializeToString,
                response_deserializer=location__service__pb2.GetLocationPhotoResponse.FromString,
                _registered_method=True)
        self.ShareLocationWithEmail = channel.unary_unary(
                '/LocationService/ShareLocationWithEmail',
                request_serializer=location__service__pb2.ShareLocationWithEmailRequest.SerializeToString,
                response_deserializer=location__service__pb2.ShareLocationWithEmailResponse.FromString,
                _registered_method=True)
        self.ShareLocationQR = channel.unary_unary(
                '/LocationService/ShareLocationQR',
                request_serializer=location__service__pb2.ShareLocationQRRequest.SerializeToString,
                response_deserializer=location__service__pb2.ShareLocationQRResponse.FromString,
                _registered_method=True)
        self.AcceptSharedLocation = channel.unary_unary(
                '/LocationService/AcceptSharedLocation',
                request_serializer=location__service__pb2.AcceptSharedLocationRequest.SerializeToString,
                response_deserializer=location__service__pb2.AcceptSharedLocationResponse.FromString,
                _registered_method=True)
        self.ViewSharedLocations = channel.unary_unary(
                '/LocationService/ViewSharedLocations',
                request_serializer=location__service__pb2.ViewSharedLocationsRequest.SerializeToString,
                response_deserializer=location__service__pb2.ViewSharedLocationsResponse.FromString,
                _registered_method=True)
        self.ViewSharedLocationGrants = channel.unary_unary(
                '/LocationService/ViewSharedLocationGrants',
                request_serializer=location__service__pb2.ViewSharedLocationGrantsRequest.SerializeToString,
                response_deserializer=location__service__pb2.ViewSharedLocationGrantsResponse.FromString,
                _registered_method=True)
        self.DeleteSharedLocation = channel.unary_unary(
                '/LocationService/DeleteSharedLocation',
                request_serializer=location__service__pb2.DeleteSharedLocationRequest.SerializeToString,
                response_deserializer=location__service__pb2.DeleteSharedLocationResponse.FromString,
                _registered_method=True)
        self.DeleteSharedLocationGrant = channel.unary_unary(
                '/LocationService/DeleteSharedLocationGrant',
                request_serializer=location__service__pb2.DeleteSharedLocationGrantRequest.SerializeToString,
                response_deserializer=location__service__pb2.DeleteSharedLocationGrantResponse.FromString,
                _registered_method=True)
        self.UpdateLocationFavorite = channel.unary_unary(
                '/LocationService/UpdateLocationFavorite',
                request_serializer=location__service__pb2.UpdateLocationFavoriteRequest.SerializeToString,
                response_deserializer=location__service__pb2.UpdateLocationFavoriteResponse.FromString,
                _registered_method=True)
        self.ValidateQRCode = channel.unary_unary(
                '/LocationService/ValidateQRCode',
                request_serializer=location__service__pb2.ValidateQRCodeRequest.SerializeToString,
                response_deserializer=location__service__pb2.ValidateQRCodeResponse.FromString,
                _registered_method=True)
        self.UpdateLocationThreshold = channel.unary_unary(
                '/LocationService/UpdateLocationThreshold',
                request_serializer=location__service__pb2.UpdateLocationThresholdRequest.SerializeToString,
                response_deserializer=location__service__pb2.UpdateLocationThresholdResponse.FromString,
                _registered_method=True)
        self.GetCalendarForTimeRange = channel.unary_unary(
                '/LocationService/GetCalendarForTimeRange',
                request_serializer=location__service__pb2.GetCalendarForTimeRangeRequest.SerializeToString,
                response_deserializer=location__service__pb2.GetCalendarForTimeRangeResponse.FromString,
                _registered_method=True)
        self.GetCalendar = channel.unary_unary(
                '/LocationService/GetCalendar',
                request_serializer=location__service__pb2.GetLocationCalendarRequest.SerializeToString,
                response_deserializer=location__service__pb2.GetLocationCalendarResponse.FromString,
                _registered_method=True)
        self.GetDay = channel.unary_unary(
                '/LocationService/GetDay',
                request_serializer=location__service__pb2.GetLocationDayRequest.SerializeToString,
                response_deserializer=location__service__pb2.GetLocationCalendarResponse.FromString,
                _registered_method=True)
        self.UpdateLocationWeatherStation = channel.unary_unary(
                '/LocationService/UpdateLocationWeatherStation',
                request_serializer=location__service__pb2.UpdateLocationWeatherStationRequest.SerializeToString,
                response_deserializer=location__service__pb2.UpdateLocationWeatherStationResponse.FromString,
                _registered_method=True)
        self.GetAvailableThresholdValues = channel.unary_unary(
                '/LocationService/GetAvailableThresholdValues',
                request_serializer=location__service__pb2.GetAvailableThresholdValuesRequest.SerializeToString,
                response_deserializer=location__service__pb2.GetAvailableThresholdValuesResponse.FromString,
                _registered_method=True)
        self.ValidateYLMCode = channel.unary_unary(
                '/LocationService/ValidateYLMCode',
                request_serializer=location__service__pb2.ValidateYLMCodeRequest.SerializeToString,
                response_deserializer=location__service__pb2.ValidateYLMCodeResponse.FromString,
                _registered_method=True)
        self.AskForYLMPhotoPermissions = channel.unary_unary(
                '/LocationService/AskForYLMPhotoPermissions',
                request_serializer=location__service__pb2.AskForYLMPhotoPermissionsRequest.SerializeToString,
                response_deserializer=location__service__pb2.AskForYLMPhotoPermissionsResponse.FromString,
                _registered_method=True)
        self.GetYardArea = channel.unary_unary(
                '/LocationService/GetYardArea',
                request_serializer=location__service__pb2.GetYardAreaRequest.SerializeToString,
                response_deserializer=location__service__pb2.GetYardAreaResponse.FromString,
                _registered_method=True)
        self.DeleteLocationByIrrigationControllerSerialNumber = channel.unary_unary(
                '/LocationService/DeleteLocationByIrrigationControllerSerialNumber',
                request_serializer=location__service__pb2.DeleteLocationByIrrigationControllerSerialNumberRequest.SerializeToString,
                response_deserializer=location__service__pb2.DeleteLocationByIrrigationControllerSerialNumberResponse.FromString,
                _registered_method=True)


class LocationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLocations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRestriction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRestriction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearRestriction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWeatherByLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClosestWeatherStations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLocationPhoto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShareLocationWithEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShareLocationQR(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptSharedLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewSharedLocations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewSharedLocationGrants(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSharedLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSharedLocationGrant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateLocationFavorite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateQRCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateLocationThreshold(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCalendarForTimeRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCalendar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateLocationWeatherStation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableThresholdValues(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateYLMCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AskForYLMPhotoPermissions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetYardArea(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteLocationByIrrigationControllerSerialNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LocationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLocation,
                    request_deserializer=location__service__pb2.GetLocationRequest.FromString,
                    response_serializer=location__service__pb2.GetLocationResponse.SerializeToString,
            ),
            'CreateLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateLocation,
                    request_deserializer=location__service__pb2.CreateLocationRequest.FromString,
                    response_serializer=location__service__pb2.CreateLocationResponse.SerializeToString,
            ),
            'DeleteLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteLocation,
                    request_deserializer=location__service__pb2.DeleteLocationRequest.FromString,
                    response_serializer=location__service__pb2.DeleteLocationResponse.SerializeToString,
            ),
            'UpdateLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateLocation,
                    request_deserializer=location__service__pb2.UpdateLocationRequest.FromString,
                    response_serializer=location__service__pb2.UpdateLocationResponse.SerializeToString,
            ),
            'ListLocations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLocations,
                    request_deserializer=location__service__pb2.ListLocationsRequest.FromString,
                    response_serializer=location__service__pb2.ListLocationsResponse.SerializeToString,
            ),
            'GetRestriction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRestriction,
                    request_deserializer=location__service__pb2.GetRestrictionRequest.FromString,
                    response_serializer=location__service__pb2.GetRestrictionResponse.SerializeToString,
            ),
            'UpdateRestriction': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRestriction,
                    request_deserializer=location__service__pb2.UpdateRestrictionRequest.FromString,
                    response_serializer=location__service__pb2.UpdateRestrictionResponse.SerializeToString,
            ),
            'ClearRestriction': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearRestriction,
                    request_deserializer=location__service__pb2.ClearRestrictionRequest.FromString,
                    response_serializer=location__service__pb2.ClearRestrictionResponse.SerializeToString,
            ),
            'GetWeatherByLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWeatherByLocation,
                    request_deserializer=location__service__pb2.GetWeatherByLocationRequest.FromString,
                    response_serializer=location__service__pb2.GetWeatherResponse.SerializeToString,
            ),
            'GetClosestWeatherStations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClosestWeatherStations,
                    request_deserializer=location__service__pb2.GetClosestWeatherStationsRequest.FromString,
                    response_serializer=location__service__pb2.GetClosestWeatherStationsResponse.SerializeToString,
            ),
            'GetLocationPhoto': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLocationPhoto,
                    request_deserializer=location__service__pb2.GetLocationPhotoRequest.FromString,
                    response_serializer=location__service__pb2.GetLocationPhotoResponse.SerializeToString,
            ),
            'ShareLocationWithEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareLocationWithEmail,
                    request_deserializer=location__service__pb2.ShareLocationWithEmailRequest.FromString,
                    response_serializer=location__service__pb2.ShareLocationWithEmailResponse.SerializeToString,
            ),
            'ShareLocationQR': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareLocationQR,
                    request_deserializer=location__service__pb2.ShareLocationQRRequest.FromString,
                    response_serializer=location__service__pb2.ShareLocationQRResponse.SerializeToString,
            ),
            'AcceptSharedLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptSharedLocation,
                    request_deserializer=location__service__pb2.AcceptSharedLocationRequest.FromString,
                    response_serializer=location__service__pb2.AcceptSharedLocationResponse.SerializeToString,
            ),
            'ViewSharedLocations': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewSharedLocations,
                    request_deserializer=location__service__pb2.ViewSharedLocationsRequest.FromString,
                    response_serializer=location__service__pb2.ViewSharedLocationsResponse.SerializeToString,
            ),
            'ViewSharedLocationGrants': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewSharedLocationGrants,
                    request_deserializer=location__service__pb2.ViewSharedLocationGrantsRequest.FromString,
                    response_serializer=location__service__pb2.ViewSharedLocationGrantsResponse.SerializeToString,
            ),
            'DeleteSharedLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSharedLocation,
                    request_deserializer=location__service__pb2.DeleteSharedLocationRequest.FromString,
                    response_serializer=location__service__pb2.DeleteSharedLocationResponse.SerializeToString,
            ),
            'DeleteSharedLocationGrant': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSharedLocationGrant,
                    request_deserializer=location__service__pb2.DeleteSharedLocationGrantRequest.FromString,
                    response_serializer=location__service__pb2.DeleteSharedLocationGrantResponse.SerializeToString,
            ),
            'UpdateLocationFavorite': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateLocationFavorite,
                    request_deserializer=location__service__pb2.UpdateLocationFavoriteRequest.FromString,
                    response_serializer=location__service__pb2.UpdateLocationFavoriteResponse.SerializeToString,
            ),
            'ValidateQRCode': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateQRCode,
                    request_deserializer=location__service__pb2.ValidateQRCodeRequest.FromString,
                    response_serializer=location__service__pb2.ValidateQRCodeResponse.SerializeToString,
            ),
            'UpdateLocationThreshold': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateLocationThreshold,
                    request_deserializer=location__service__pb2.UpdateLocationThresholdRequest.FromString,
                    response_serializer=location__service__pb2.UpdateLocationThresholdResponse.SerializeToString,
            ),
            'GetCalendarForTimeRange': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCalendarForTimeRange,
                    request_deserializer=location__service__pb2.GetCalendarForTimeRangeRequest.FromString,
                    response_serializer=location__service__pb2.GetCalendarForTimeRangeResponse.SerializeToString,
            ),
            'GetCalendar': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCalendar,
                    request_deserializer=location__service__pb2.GetLocationCalendarRequest.FromString,
                    response_serializer=location__service__pb2.GetLocationCalendarResponse.SerializeToString,
            ),
            'GetDay': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDay,
                    request_deserializer=location__service__pb2.GetLocationDayRequest.FromString,
                    response_serializer=location__service__pb2.GetLocationCalendarResponse.SerializeToString,
            ),
            'UpdateLocationWeatherStation': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateLocationWeatherStation,
                    request_deserializer=location__service__pb2.UpdateLocationWeatherStationRequest.FromString,
                    response_serializer=location__service__pb2.UpdateLocationWeatherStationResponse.SerializeToString,
            ),
            'GetAvailableThresholdValues': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableThresholdValues,
                    request_deserializer=location__service__pb2.GetAvailableThresholdValuesRequest.FromString,
                    response_serializer=location__service__pb2.GetAvailableThresholdValuesResponse.SerializeToString,
            ),
            'ValidateYLMCode': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateYLMCode,
                    request_deserializer=location__service__pb2.ValidateYLMCodeRequest.FromString,
                    response_serializer=location__service__pb2.ValidateYLMCodeResponse.SerializeToString,
            ),
            'AskForYLMPhotoPermissions': grpc.unary_unary_rpc_method_handler(
                    servicer.AskForYLMPhotoPermissions,
                    request_deserializer=location__service__pb2.AskForYLMPhotoPermissionsRequest.FromString,
                    response_serializer=location__service__pb2.AskForYLMPhotoPermissionsResponse.SerializeToString,
            ),
            'GetYardArea': grpc.unary_unary_rpc_method_handler(
                    servicer.GetYardArea,
                    request_deserializer=location__service__pb2.GetYardAreaRequest.FromString,
                    response_serializer=location__service__pb2.GetYardAreaResponse.SerializeToString,
            ),
            'DeleteLocationByIrrigationControllerSerialNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteLocationByIrrigationControllerSerialNumber,
                    request_deserializer=location__service__pb2.DeleteLocationByIrrigationControllerSerialNumberRequest.FromString,
                    response_serializer=location__service__pb2.DeleteLocationByIrrigationControllerSerialNumberResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LocationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('LocationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LocationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocationService/GetLocation',
            location__service__pb2.GetLocationRequest.SerializeToString,
            location__service__pb2.GetLocationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocationService/CreateLocation',
            location__service__pb2.CreateLocationRequest.SerializeToString,
            location__service__pb2.CreateLocationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocationService/DeleteLocation',
            location__service__pb2.DeleteLocationRequest.SerializeToString,
            location__service__pb2.DeleteLocationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocationService/UpdateLocation',
            location__service__pb2.UpdateLocationRequest.SerializeToString,
            location__service__pb2.UpdateLocationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLocations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocationService/ListLocations',
            location__service__pb2.ListLocationsRequest.SerializeToString,
            location__service__pb2.ListLocationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRestriction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocationService/GetRestriction',
            location__service__pb2.GetRestrictionRequest.SerializeToString,
            location__service__pb2.GetRestrictionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRestriction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocationService/UpdateRestriction',
            location__service__pb2.UpdateRestrictionRequest.SerializeToString,
            location__service__pb2.UpdateRestrictionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearRestriction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocationService/ClearRestriction',
            location__service__pb2.ClearRestrictionRequest.SerializeToString,
            location__service__pb2.ClearRestrictionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWeatherByLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocationService/GetWeatherByLocation',
            location__service__pb2.GetWeatherByLocationRequest.SerializeToString,
            location__service__pb2.GetWeatherResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClosestWeatherStations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocationService/GetClosestWeatherStations',
            location__service__pb2.GetClosestWeatherStationsRequest.SerializeToString,
            location__service__pb2.GetClosestWeatherStationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLocationPhoto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocationService/GetLocationPhoto',
            location__service__pb2.GetLocationPhotoRequest.SerializeToString,
            location__service__pb2.GetLocationPhotoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShareLocationWithEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocationService/ShareLocationWithEmail',
            location__service__pb2.ShareLocationWithEmailRequest.SerializeToString,
            location__service__pb2.ShareLocationWithEmailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShareLocationQR(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocationService/ShareLocationQR',
            location__service__pb2.ShareLocationQRRequest.SerializeToString,
            location__service__pb2.ShareLocationQRResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcceptSharedLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocationService/AcceptSharedLocation',
            location__service__pb2.AcceptSharedLocationRequest.SerializeToString,
            location__service__pb2.AcceptSharedLocationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewSharedLocations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocationService/ViewSharedLocations',
            location__service__pb2.ViewSharedLocationsRequest.SerializeToString,
            location__service__pb2.ViewSharedLocationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewSharedLocationGrants(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocationService/ViewSharedLocationGrants',
            location__service__pb2.ViewSharedLocationGrantsRequest.SerializeToString,
            location__service__pb2.ViewSharedLocationGrantsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSharedLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocationService/DeleteSharedLocation',
            location__service__pb2.DeleteSharedLocationRequest.SerializeToString,
            location__service__pb2.DeleteSharedLocationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSharedLocationGrant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocationService/DeleteSharedLocationGrant',
            location__service__pb2.DeleteSharedLocationGrantRequest.SerializeToString,
            location__service__pb2.DeleteSharedLocationGrantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateLocationFavorite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocationService/UpdateLocationFavorite',
            location__service__pb2.UpdateLocationFavoriteRequest.SerializeToString,
            location__service__pb2.UpdateLocationFavoriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateQRCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocationService/ValidateQRCode',
            location__service__pb2.ValidateQRCodeRequest.SerializeToString,
            location__service__pb2.ValidateQRCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateLocationThreshold(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocationService/UpdateLocationThreshold',
            location__service__pb2.UpdateLocationThresholdRequest.SerializeToString,
            location__service__pb2.UpdateLocationThresholdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCalendarForTimeRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocationService/GetCalendarForTimeRange',
            location__service__pb2.GetCalendarForTimeRangeRequest.SerializeToString,
            location__service__pb2.GetCalendarForTimeRangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCalendar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocationService/GetCalendar',
            location__service__pb2.GetLocationCalendarRequest.SerializeToString,
            location__service__pb2.GetLocationCalendarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocationService/GetDay',
            location__service__pb2.GetLocationDayRequest.SerializeToString,
            location__service__pb2.GetLocationCalendarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateLocationWeatherStation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocationService/UpdateLocationWeatherStation',
            location__service__pb2.UpdateLocationWeatherStationRequest.SerializeToString,
            location__service__pb2.UpdateLocationWeatherStationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvailableThresholdValues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocationService/GetAvailableThresholdValues',
            location__service__pb2.GetAvailableThresholdValuesRequest.SerializeToString,
            location__service__pb2.GetAvailableThresholdValuesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateYLMCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocationService/ValidateYLMCode',
            location__service__pb2.ValidateYLMCodeRequest.SerializeToString,
            location__service__pb2.ValidateYLMCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AskForYLMPhotoPermissions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocationService/AskForYLMPhotoPermissions',
            location__service__pb2.AskForYLMPhotoPermissionsRequest.SerializeToString,
            location__service__pb2.AskForYLMPhotoPermissionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetYardArea(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocationService/GetYardArea',
            location__service__pb2.GetYardAreaRequest.SerializeToString,
            location__service__pb2.GetYardAreaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteLocationByIrrigationControllerSerialNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LocationService/DeleteLocationByIrrigationControllerSerialNumber',
            location__service__pb2.DeleteLocationByIrrigationControllerSerialNumberRequest.SerializeToString,
            location__service__pb2.DeleteLocationByIrrigationControllerSerialNumberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
