# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: location.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "location.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0elocation.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\ncore.proto\x1a\x18location_threshold.proto\x1a\x0c\x64\x65vice.proto\x1a\x17schedule_criteria.proto\x1a\x13skip_sequence.proto\x1a\x15weather_station.proto\x1a\x1birrigation_controller.proto"\x94\x04\n\x08Location\x12\n\n\x02id\x18\x01 \x01(\t\x12+\n\x07\x63reated\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07updated\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x15\n\tdevice_id\x18\x05 \x03(\tB\x02\x18\x01\x12\x1c\n\x07\x64\x65vices\x18\x0e \x03(\x0b\x32\x0b.DeviceInfo\x12\x19\n\x07\x61\x64\x64ress\x18\x06 \x01(\x0b\x32\x08.Address\x12\x1c\n\tgeo_point\x18\x07 \x01(\x0b\x32\t.GeoPoint\x12\x10\n\x08photo_id\x18\x08 \x01(\t\x12\x11\n\ttime_zone\x18\t \x01(\t\x12(\n\x1cinclude_all_weather_stations\x18\n \x01(\x08\x42\x02\x18\x01\x12\r\n\x05owner\x18\x0c \x01(\x08\x12%\n\tthreshold\x18\r \x03(\x0b\x32\x12.LocationThreshold\x12\x1c\n\x10subscription_ids\x18\x0f \x03(\tB\x02\x18\x01\x12\x38\n\x12weather_station_id\x18\x10 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12I\n irrigation_controller_properties\x18\x11 \x01(\x0b\x32\x1f.IrrigationControllerProperties"A\n\nDeviceInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x19\n\x04type\x18\x02 \x01(\x0e\x32\x0b.DeviceType\x12\x0c\n\x04name\x18\x03 \x01(\t"\x89\x02\n\x0bWateringDay\x12\x13\n\x0bschedule_id\x18\x01 \x01(\t\x12$\n\rschedule_type\x18\x02 \x01(\x0e\x32\r.ScheduleType\x12\x13\n\x04\x64\x61te\x18\x03 \x01(\x0b\x32\x05.Date\x12\x0f\n\x07skipped\x18\x04 \x01(\x08\x12\x15\n\rschedule_name\x18\x06 \x01(\t\x12\x19\n\nstart_time\x18\x07 \x01(\x0b\x32\x05.Time\x12\x17\n\x08\x65nd_time\x18\x08 \x01(\x0b\x32\x05.Time"N\n\tSkipCause\x12\n\n\x06MANUAL\x10\x00\x12\n\n\x06\x46REEZE\x10\x01\x12\x08\n\x04WIND\x10\x02\x12\x0b\n\x07\x43LIMATE\x10\x03\x12\x08\n\x04RAIN\x10\x04\x12\x08\n\x04NONE\x10\x05\x42\x1b\n\x17\x63om.rachio.api.locationP\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "location_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"\n\027com.rachio.api.locationP\001"
    _globals["_LOCATION"].fields_by_name["device_id"]._loaded_options = None
    _globals["_LOCATION"].fields_by_name["device_id"]._serialized_options = b"\030\001"
    _globals["_LOCATION"].fields_by_name[
        "include_all_weather_stations"
    ]._loaded_options = None
    _globals["_LOCATION"].fields_by_name[
        "include_all_weather_stations"
    ]._serialized_options = b"\030\001"
    _globals["_LOCATION"].fields_by_name["subscription_ids"]._loaded_options = None
    _globals["_LOCATION"].fields_by_name[
        "subscription_ids"
    ]._serialized_options = b"\030\001"
    _globals["_LOCATION"]._serialized_start = 234
    _globals["_LOCATION"]._serialized_end = 766
    _globals["_DEVICEINFO"]._serialized_start = 768
    _globals["_DEVICEINFO"]._serialized_end = 833
    _globals["_WATERINGDAY"]._serialized_start = 836
    _globals["_WATERINGDAY"]._serialized_end = 1101
    _globals["_WATERINGDAY_SKIPCAUSE"]._serialized_start = 1023
    _globals["_WATERINGDAY_SKIPCAUSE"]._serialized_end = 1101
# @@protoc_insertion_point(module_scope)
