# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: location_threshold.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'location_threshold.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18location_threshold.proto\"@\n\x11LocationThreshold\x12\x1c\n\x04name\x18\x01 \x01(\x0e\x32\x0e.ThresholdName\x12\r\n\x05value\x18\x02 \x01(\x01*\x7f\n\rThresholdName\x12\'\n#IRRIGATION_CONTROLLER_PRECIPITATION\x10\x00\x12%\n!IRRIGATION_CONTROLLER_TEMPERATURE\x10\x01\x12\x1e\n\x1aIRRIGATION_CONTROLLER_WIND\x10\x02\x42\x1b\n\x17\x63om.rachio.api.locationP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'location_threshold_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027com.rachio.api.locationP\001'
  _globals['_THRESHOLDNAME']._serialized_start=94
  _globals['_THRESHOLDNAME']._serialized_end=221
  _globals['_LOCATIONTHRESHOLD']._serialized_start=28
  _globals['_LOCATIONTHRESHOLD']._serialized_end=92
# @@protoc_insertion_point(module_scope)
