# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: provision.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "provision.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0fprovision.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\ncore.proto\x1a\x1egoogle/protobuf/wrappers.proto"\xd5\x05\n\tProvision\x12\x15\n\rserial_number\x18\x01 \x01(\t\x12\x0b\n\x03pin\x18\x02 \x01(\t\x12 \n\x06status\x18\x03 \x01(\x0e\x32\x10.ProvisionStatus\x12#\n\x0cmanufacturer\x18\x04 \x01(\x0e\x32\r.Manufacturer\x12)\n\x03mac\x18\x05 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\r\n\x05model\x18\x06 \x01(\t\x12\x36\n\x10\x66irmware_version\x18\x07 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x0b\n\x03pro\x18\x08 \x01(\x08\x12!\n\x19weather_intelligence_plus\x18\t \x01(\x08\x12\x13\n\x0bhomekit_pin\x18\n \x01(\t\x12\x31\n\x0btest_status\x18\x0b \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x31\n\x0btest_result\x18\x0c \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x36\n\x12manufacturing_date\x18\r \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07\x63reated\x18\x0e \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07updated\x18\x0f \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x35\n\x0fqr_code_payload\x18\x10 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x41\n\x1blast_known_firmware_version\x18\x11 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x34\n\x10refurbished_date\x18\x12 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*\xb7\x01\n\x0fProvisionStatus\x12\r\n\tAVAILABLE\x10\x00\x12\x0c\n\x08\x41SSIGNED\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\x12\x0c\n\x08\x43ONSUMED\x10\x03\x12\x0b\n\x07REMOVED\x10\x04\x12\x10\n\x0cRETURN_STOCK\x10\x05\x12\x10\n\x0cREFURB_STOCK\x10\x06\x12\x0c\n\x08RECYCLED\x10\x07\x12\x16\n\x12PCBA_TESTED_FAILED\x10\x08\x12\x16\n\x12PCBA_TESTED_PASSED\x10\t*^\n\x0cManufacturer\x12\x0c\n\x08\x43REATION\x10\x00\x12\x0b\n\x07VERGENT\x10\x01\x12\x0f\n\x0b\x41STEELFLASH\x10\x02\x12\x10\n\x0c\x43OMPUTIME_CN\x10\x03\x12\x10\n\x0c\x43OMPUTIME_MY\x10\x04\x42\x1c\n\x18\x63om.rachio.api.provisionP\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "provision_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"\n\030com.rachio.api.provisionP\001"
    _globals["_PROVISIONSTATUS"]._serialized_start = 825
    _globals["_PROVISIONSTATUS"]._serialized_end = 1008
    _globals["_MANUFACTURER"]._serialized_start = 1010
    _globals["_MANUFACTURER"]._serialized_end = 1104
    _globals["_PROVISION"]._serialized_start = 97
    _globals["_PROVISION"]._serialized_end = 822
# @@protoc_insertion_point(module_scope)
