# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import schedule_service_pb2 as schedule__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in schedule_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScheduleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSchedule = channel.unary_unary(
                '/ScheduleService/CreateSchedule',
                request_serializer=schedule__service__pb2.CreateScheduleRequest.SerializeToString,
                response_deserializer=schedule__service__pb2.CreateScheduleResponse.FromString,
                _registered_method=True)
        self.GetSchedules = channel.unary_unary(
                '/ScheduleService/GetSchedules',
                request_serializer=schedule__service__pb2.GetSchedulesRequest.SerializeToString,
                response_deserializer=schedule__service__pb2.GetSchedulesResponse.FromString,
                _registered_method=True)
        self.UpdateSchedule = channel.unary_unary(
                '/ScheduleService/UpdateSchedule',
                request_serializer=schedule__service__pb2.UpdateScheduleRequest.SerializeToString,
                response_deserializer=schedule__service__pb2.UpdateScheduleResponse.FromString,
                _registered_method=True)
        self.DeleteSchedule = channel.unary_unary(
                '/ScheduleService/DeleteSchedule',
                request_serializer=schedule__service__pb2.DeleteScheduleRequest.SerializeToString,
                response_deserializer=schedule__service__pb2.DeleteScheduleResponse.FromString,
                _registered_method=True)
        self.RunSchedule = channel.unary_unary(
                '/ScheduleService/RunSchedule',
                request_serializer=schedule__service__pb2.RunScheduleRequest.SerializeToString,
                response_deserializer=schedule__service__pb2.RunScheduleResponse.FromString,
                _registered_method=True)
        self.CopySchedule = channel.unary_unary(
                '/ScheduleService/CopySchedule',
                request_serializer=schedule__service__pb2.CopyScheduleRequest.SerializeToString,
                response_deserializer=schedule__service__pb2.CopyScheduleResponse.FromString,
                _registered_method=True)
        self.SetSkip = channel.unary_unary(
                '/ScheduleService/SetSkip',
                request_serializer=schedule__service__pb2.SetSkipRequest.SerializeToString,
                response_deserializer=schedule__service__pb2.SetSkipResponse.FromString,
                _registered_method=True)
        self.GetScheduleRuns = channel.unary_unary(
                '/ScheduleService/GetScheduleRuns',
                request_serializer=schedule__service__pb2.GetScheduleRunsRequest.SerializeToString,
                response_deserializer=schedule__service__pb2.GetScheduleRunsResponse.FromString,
                _registered_method=True)
        self.PreviewSchedule = channel.unary_unary(
                '/ScheduleService/PreviewSchedule',
                request_serializer=schedule__service__pb2.PreviewScheduleRequest.SerializeToString,
                response_deserializer=schedule__service__pb2.PreviewScheduleResponse.FromString,
                _registered_method=True)
        self.GetLocationsAndDevicesForSchedule = channel.unary_unary(
                '/ScheduleService/GetLocationsAndDevicesForSchedule',
                request_serializer=schedule__service__pb2.GetLocationsAndDevicesForScheduleRequest.SerializeToString,
                response_deserializer=schedule__service__pb2.GetLocationsAndDevicesForScheduleResponse.FromString,
                _registered_method=True)
        self.GetScheduleAdjustment = channel.unary_unary(
                '/ScheduleService/GetScheduleAdjustment',
                request_serializer=schedule__service__pb2.GetScheduleAdjustmentRequest.SerializeToString,
                response_deserializer=schedule__service__pb2.GetScheduleAdjustmentResponse.FromString,
                _registered_method=True)
        self.ListScheduleAdjustmentsByDeviceId = channel.unary_unary(
                '/ScheduleService/ListScheduleAdjustmentsByDeviceId',
                request_serializer=schedule__service__pb2.ListScheduleAdjustmentsByDeviceIdRequest.SerializeToString,
                response_deserializer=schedule__service__pb2.ListScheduleAdjustmentsByDeviceIdResponse.FromString,
                _registered_method=True)
        self.UpdateScheduleAdjustment = channel.unary_unary(
                '/ScheduleService/UpdateScheduleAdjustment',
                request_serializer=schedule__service__pb2.UpdateScheduleAdjustmentRequest.SerializeToString,
                response_deserializer=schedule__service__pb2.UpdateScheduleAdjustmentResponse.FromString,
                _registered_method=True)


class ScheduleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchedules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CopySchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSkip(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScheduleRuns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PreviewSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLocationsAndDevicesForSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScheduleAdjustment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListScheduleAdjustmentsByDeviceId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateScheduleAdjustment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScheduleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSchedule,
                    request_deserializer=schedule__service__pb2.CreateScheduleRequest.FromString,
                    response_serializer=schedule__service__pb2.CreateScheduleResponse.SerializeToString,
            ),
            'GetSchedules': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchedules,
                    request_deserializer=schedule__service__pb2.GetSchedulesRequest.FromString,
                    response_serializer=schedule__service__pb2.GetSchedulesResponse.SerializeToString,
            ),
            'UpdateSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSchedule,
                    request_deserializer=schedule__service__pb2.UpdateScheduleRequest.FromString,
                    response_serializer=schedule__service__pb2.UpdateScheduleResponse.SerializeToString,
            ),
            'DeleteSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSchedule,
                    request_deserializer=schedule__service__pb2.DeleteScheduleRequest.FromString,
                    response_serializer=schedule__service__pb2.DeleteScheduleResponse.SerializeToString,
            ),
            'RunSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.RunSchedule,
                    request_deserializer=schedule__service__pb2.RunScheduleRequest.FromString,
                    response_serializer=schedule__service__pb2.RunScheduleResponse.SerializeToString,
            ),
            'CopySchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.CopySchedule,
                    request_deserializer=schedule__service__pb2.CopyScheduleRequest.FromString,
                    response_serializer=schedule__service__pb2.CopyScheduleResponse.SerializeToString,
            ),
            'SetSkip': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSkip,
                    request_deserializer=schedule__service__pb2.SetSkipRequest.FromString,
                    response_serializer=schedule__service__pb2.SetSkipResponse.SerializeToString,
            ),
            'GetScheduleRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScheduleRuns,
                    request_deserializer=schedule__service__pb2.GetScheduleRunsRequest.FromString,
                    response_serializer=schedule__service__pb2.GetScheduleRunsResponse.SerializeToString,
            ),
            'PreviewSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.PreviewSchedule,
                    request_deserializer=schedule__service__pb2.PreviewScheduleRequest.FromString,
                    response_serializer=schedule__service__pb2.PreviewScheduleResponse.SerializeToString,
            ),
            'GetLocationsAndDevicesForSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLocationsAndDevicesForSchedule,
                    request_deserializer=schedule__service__pb2.GetLocationsAndDevicesForScheduleRequest.FromString,
                    response_serializer=schedule__service__pb2.GetLocationsAndDevicesForScheduleResponse.SerializeToString,
            ),
            'GetScheduleAdjustment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScheduleAdjustment,
                    request_deserializer=schedule__service__pb2.GetScheduleAdjustmentRequest.FromString,
                    response_serializer=schedule__service__pb2.GetScheduleAdjustmentResponse.SerializeToString,
            ),
            'ListScheduleAdjustmentsByDeviceId': grpc.unary_unary_rpc_method_handler(
                    servicer.ListScheduleAdjustmentsByDeviceId,
                    request_deserializer=schedule__service__pb2.ListScheduleAdjustmentsByDeviceIdRequest.FromString,
                    response_serializer=schedule__service__pb2.ListScheduleAdjustmentsByDeviceIdResponse.SerializeToString,
            ),
            'UpdateScheduleAdjustment': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateScheduleAdjustment,
                    request_deserializer=schedule__service__pb2.UpdateScheduleAdjustmentRequest.FromString,
                    response_serializer=schedule__service__pb2.UpdateScheduleAdjustmentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ScheduleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ScheduleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScheduleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ScheduleService/CreateSchedule',
            schedule__service__pb2.CreateScheduleRequest.SerializeToString,
            schedule__service__pb2.CreateScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSchedules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ScheduleService/GetSchedules',
            schedule__service__pb2.GetSchedulesRequest.SerializeToString,
            schedule__service__pb2.GetSchedulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ScheduleService/UpdateSchedule',
            schedule__service__pb2.UpdateScheduleRequest.SerializeToString,
            schedule__service__pb2.UpdateScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ScheduleService/DeleteSchedule',
            schedule__service__pb2.DeleteScheduleRequest.SerializeToString,
            schedule__service__pb2.DeleteScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ScheduleService/RunSchedule',
            schedule__service__pb2.RunScheduleRequest.SerializeToString,
            schedule__service__pb2.RunScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CopySchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ScheduleService/CopySchedule',
            schedule__service__pb2.CopyScheduleRequest.SerializeToString,
            schedule__service__pb2.CopyScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSkip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ScheduleService/SetSkip',
            schedule__service__pb2.SetSkipRequest.SerializeToString,
            schedule__service__pb2.SetSkipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScheduleRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ScheduleService/GetScheduleRuns',
            schedule__service__pb2.GetScheduleRunsRequest.SerializeToString,
            schedule__service__pb2.GetScheduleRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PreviewSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ScheduleService/PreviewSchedule',
            schedule__service__pb2.PreviewScheduleRequest.SerializeToString,
            schedule__service__pb2.PreviewScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLocationsAndDevicesForSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ScheduleService/GetLocationsAndDevicesForSchedule',
            schedule__service__pb2.GetLocationsAndDevicesForScheduleRequest.SerializeToString,
            schedule__service__pb2.GetLocationsAndDevicesForScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScheduleAdjustment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ScheduleService/GetScheduleAdjustment',
            schedule__service__pb2.GetScheduleAdjustmentRequest.SerializeToString,
            schedule__service__pb2.GetScheduleAdjustmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListScheduleAdjustmentsByDeviceId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ScheduleService/ListScheduleAdjustmentsByDeviceId',
            schedule__service__pb2.ListScheduleAdjustmentsByDeviceIdRequest.SerializeToString,
            schedule__service__pb2.ListScheduleAdjustmentsByDeviceIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateScheduleAdjustment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ScheduleService/UpdateScheduleAdjustment',
            schedule__service__pb2.UpdateScheduleAdjustmentRequest.SerializeToString,
            schedule__service__pb2.UpdateScheduleAdjustmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
