# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schedule_zone_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "schedule_zone_info.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x18schedule_zone_info.proto"\xa6\x01\n\x10ScheduleZoneInfo\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0f\n\x07zone_id\x18\x02 \x01(\t\x12\x10\n\x08order_id\x18\x03 \x01(\x05\x12\x15\n\rwatering_time\x18\x04 \x01(\x05\x12#\n\x1b\x66lex_aggression_coefficient\x18\x05 \x01(\x01\x12 \n\x18\x66lex_runtime_coefficient\x18\x06 \x01(\x01\x42\x1b\n\x17\x63om.rachio.api.scheduleP\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "schedule_zone_info_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"\n\027com.rachio.api.scheduleP\001"
    _globals["_SCHEDULEZONEINFO"]._serialized_start = 29
    _globals["_SCHEDULEZONEINFO"]._serialized_end = 195
# @@protoc_insertion_point(module_scope)
