# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schedule.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'schedule.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import schedule_criteria_pb2 as schedule__criteria__pb2
import schedule_restriction_criteria_pb2 as schedule__restriction__criteria__pb2
import schedule_zone_info_pb2 as schedule__zone__info__pb2
import schedule_adjustment_pb2 as schedule__adjustment__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eschedule.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x17schedule_criteria.proto\x1a#schedule_restriction_criteria.proto\x1a\x18schedule_zone_info.proto\x1a\x19schedule_adjustment.proto\"\xe6\x04\n\x08Schedule\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12,\n\x11schedule_criteria\x18\x03 \x01(\x0b\x32\x11.ScheduleCriteria\x12\x43\n\x1dschedule_restriction_criteria\x18\x04 \x01(\x0b\x32\x1c.ScheduleRestrictionCriteria\x12$\n\tzone_info\x18\x05 \x03(\x0b\x32\x11.ScheduleZoneInfo\x12\x0f\n\x07\x65nabled\x18\x06 \x01(\x08\x12+\n\x07\x63reated\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07updated\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07summary\x18\t \x01(\t\x12+\n\x05\x63olor\x18\n \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x41\n\x17koppen_reduction_factor\x18\x0b \x01(\x0b\x32\x1c.google.protobuf.DoubleValueB\x02\x18\x01\x12-\n%annual_start_on_notifications_enabled\x18\x0c \x01(\x08\x12+\n#annual_end_on_notifications_enabled\x18\r \x01(\x08\x12,\n$use_forecast_weather_for_precip_skip\x18\x0e \x01(\x08\x12\x31\n\x14schedule_adjustments\x18\x0f \x03(\x0b\x32\x13.ScheduleAdjustmentB\x1b\n\x17\x63om.rachio.api.scheduleP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schedule_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027com.rachio.api.scheduleP\001'
  _globals['_SCHEDULE'].fields_by_name['koppen_reduction_factor']._loaded_options = None
  _globals['_SCHEDULE'].fields_by_name['koppen_reduction_factor']._serialized_options = b'\030\001'
  _globals['_SCHEDULE']._serialized_start=199
  _globals['_SCHEDULE']._serialized_end=813
# @@protoc_insertion_point(module_scope)
