# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schedule_run.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "schedule_run.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12schedule_run.proto\x1a\x17schedule_criteria.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto"\x92\x02\n\x0bScheduleRun\x12\x13\n\x0bschedule_id\x18\x01 \x01(\t\x12.\n\nstart_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12$\n\rschedule_type\x18\x04 \x01(\x0e\x32\r.ScheduleType\x12#\n\tzone_runs\x18\x05 \x03(\x0b\x32\x10.ScheduleZoneRun\x12\x33\n\rschedule_name\x18\x06 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x10\n\x08icon_url\x18\x07 \x01(\t"\xd2\x01\n\x0fScheduleZoneRun\x12\x16\n\x04type\x18\x01 \x01(\x0e\x32\x08.RunType\x12.\n\nstart_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tzone_name\x18\x04 \x01(\t\x12\x0f\n\x07zone_id\x18\x05 \x01(\t\x12\x10\n\x08photo_id\x18\x06 \x01(\t\x12\x13\n\x0bzone_number\x18\x07 \x01(\x05*-\n\x07RunType\x12\x0c\n\x08IRRIGATE\x10\x00\x12\t\n\x05\x43YCLE\x10\x01\x12\t\n\x05PAUSE\x10\x02\x42\x1b\n\x17\x63om.rachio.api.scheduleP\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "schedule_run_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"\n\027com.rachio.api.scheduleP\001"
    _globals["_RUNTYPE"]._serialized_start = 602
    _globals["_RUNTYPE"]._serialized_end = 647
    _globals["_SCHEDULERUN"]._serialized_start = 113
    _globals["_SCHEDULERUN"]._serialized_end = 387
    _globals["_SCHEDULEZONERUN"]._serialized_start = 390
    _globals["_SCHEDULEZONERUN"]._serialized_end = 600
# @@protoc_insertion_point(module_scope)
