# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import device_pb2 as device__pb2
import flow_provision_model_pb2 as flow__provision__model__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csensor.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0c\x64\x65vice.proto\x1a\x1a\x66low_provision_model.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xc2\x03\n\x0cLinkedSensor\x12\n\n\x02id\x18\x01 \x01(\t\x12(\n\x0fwiring_position\x18\x02 \x01(\x0e\x32\x0f.WiringPosition\x12*\n\x04make\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12+\n\x05model\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12-\n\x07kfactor\x18\x05 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12,\n\x06offset\x18\x06 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12\x0f\n\x07\x65nabled\x18\x07 \x01(\x08\x12\x33\n\x0bsensor_type\x18\x08 \x01(\x0e\x32\x1e.LinkedSensor.LinkedSensorType\x12+\n\x07\x63reated\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07updated\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"&\n\x10LinkedSensorType\x12\x08\n\x04RAIN\x10\x00\x12\x08\n\x04\x46LOW\x10\x01\"V\n\nFlowSensor\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04make\x18\x02 \x01(\t\x12\r\n\x05model\x18\x03 \x01(\t\x12\x0f\n\x07kfactor\x18\x04 \x01(\x01\x12\x0e\n\x06offset\x18\x05 \x01(\x01\"u\n\x19NascentWirelessFlowSensor\x12\x15\n\rserial_number\x18\x01 \x01(\t\x12\x13\n\x0bmac_address\x18\x02 \x01(\t\x12\x19\n\x05model\x18\x03 \x01(\x0e\x32\n.FlowModel\x12\x11\n\tactivated\x18\x04 \x01(\x08\"\xed\x01\n\x12WirelessFlowSensor\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0bmac_address\x18\x03 \x01(\t\x12\x15\n\rserial_number\x18\x04 \x01(\t\x12\x0b\n\x03pin\x18\x05 \x01(\t\x12\x13\n\x0blocation_id\x18\x06 \x01(\t\x12\x15\n\rcontroller_id\x18\x07 \x01(\t\x12+\n\x07\x63reated\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07updated\x18\t \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x19\n\x15\x63om.rachio.api.deviceP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.rachio.api.deviceP\001'
  _globals['_LINKEDSENSOR']._serialized_start=124
  _globals['_LINKEDSENSOR']._serialized_end=574
  _globals['_LINKEDSENSOR_LINKEDSENSORTYPE']._serialized_start=536
  _globals['_LINKEDSENSOR_LINKEDSENSORTYPE']._serialized_end=574
  _globals['_FLOWSENSOR']._serialized_start=576
  _globals['_FLOWSENSOR']._serialized_end=662
  _globals['_NASCENTWIRELESSFLOWSENSOR']._serialized_start=664
  _globals['_NASCENTWIRELESSFLOWSENSOR']._serialized_end=781
  _globals['_WIRELESSFLOWSENSOR']._serialized_start=784
  _globals['_WIRELESSFLOWSENSOR']._serialized_end=1021
# @@protoc_insertion_point(module_scope)
