# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: skip_sequence.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "skip_sequence.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13skip_sequence.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto"\xf7\x02\n\x0cSkipSequence\x12\n\n\x02id\x18\x01 \x01(\t\x12\x31\n\x0bschedule_id\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12.\n\nstart_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12&\n\x05\x63\x61use\x18\x05 \x01(\x0e\x32\x17.SkipSequence.SkipCause\x12\x10\n\x08\x64isabled\x18\x06 \x01(\x08\x12\r\n\x05\x66orce\x18\x07 \x01(\x08\x12\x1a\n\x12weather_station_id\x18\x08 \x01(\t\x12\x15\n\rschedule_name\x18\t \x01(\t"N\n\tSkipCause\x12\n\n\x06MANUAL\x10\x00\x12\n\n\x06\x46REEZE\x10\x01\x12\x08\n\x04WIND\x10\x02\x12\x0b\n\x07\x43LIMATE\x10\x03\x12\x08\n\x04RAIN\x10\x04\x12\x08\n\x04NONE\x10\x05\x42\x1b\n\x17\x63om.rachio.api.scheduleP\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "skip_sequence_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"\n\027com.rachio.api.scheduleP\001"
    _globals["_SKIPSEQUENCE"]._serialized_start = 89
    _globals["_SKIPSEQUENCE"]._serialized_end = 464
    _globals["_SKIPSEQUENCE_SKIPCAUSE"]._serialized_start = 386
    _globals["_SKIPSEQUENCE_SKIPCAUSE"]._serialized_end = 464
# @@protoc_insertion_point(module_scope)
