# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import user_preference_pb2 as user__preference__pb2
import core_pb2 as core__pb2
import device_pb2 as device__pb2
import auth_extension_pb2 as auth__extension__pb2
import media_model_pb2 as media__model__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15user_preference.proto\x1a\ncore.proto\x1a\x0c\x64\x65vice.proto\x1a\x14\x61uth_extension.proto\x1a\x11media_model.proto\"\xdf\x04\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x15\n\remail_address\x18\x04 \x01(\t\x12#\n\npreference\x18\x05 \x03(\x0b\x32\x0f.UserPreference\x12+\n\x07\x63reated\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07updated\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x14\n\x0cphone_number\x18\x08 \x01(\t\x12\x10\n\x08username\x18\n \x01(\t\x12\x0b\n\x03pro\x18\x0b \x01(\x08\x12\x17\n\x04role\x18\x0c \x03(\x0e\x32\t.AuthRole\x12\x33\n\x12privacy_constraint\x18\r \x01(\x0e\x32\x17.User.PrivacyConstraint\x12$\n\nmembership\x18\x0e \x01(\x0b\x32\x10.User.Membership\x12$\n\rphoto_summary\x18\x0f \x01(\x0b\x32\r.PhotoSummary\x1a\x85\x01\n\nMembership\x12\x17\n\x0forganization_id\x18\x01 \x01(\t\x12#\n\x04role\x18\x02 \x01(\x0e\x32\x15.User.Membership.Role\x12\x11\n\tmember_id\x18\x03 \x01(\t\"&\n\x04Role\x12\x08\n\x04TECH\x10\x00\x12\t\n\x05\x41\x44MIN\x10\x01\x12\t\n\x05OWNER\x10\x02\"1\n\x11PrivacyConstraint\x12\x08\n\x04NONE\x10\x00\x12\x12\n\x0e\x44O_NOT_USE_PII\x10\x01J\x04\x08\t\x10\n\"K\n\nEventToken\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x1d\n\x04type\x18\x03 \x01(\x0e\x32\x0f.EventTokenType*T\n\x0e\x45ventTokenType\x12\x15\n\x11NO_TYPE_SUBMITTED\x10\x00\x12\x07\n\x03WEB\x10\x01\x12\x07\n\x03IOS\x10\x02\x12\x0b\n\x07\x41NDROID\x10\x03\x12\x0c\n\x08IOS_MQTT\x10\x04\x42\x17\n\x13\x63om.rachio.api.userP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.rachio.api.userP\001'
  _globals['_EVENTTOKENTYPE']._serialized_start=824
  _globals['_EVENTTOKENTYPE']._serialized_end=908
  _globals['_USER']._serialized_start=138
  _globals['_USER']._serialized_end=745
  _globals['_USER_MEMBERSHIP']._serialized_start=555
  _globals['_USER_MEMBERSHIP']._serialized_end=688
  _globals['_USER_MEMBERSHIP_ROLE']._serialized_start=650
  _globals['_USER_MEMBERSHIP_ROLE']._serialized_end=688
  _globals['_USER_PRIVACYCONSTRAINT']._serialized_start=690
  _globals['_USER_PRIVACYCONSTRAINT']._serialized_end=739
  _globals['_EVENTTOKEN']._serialized_start=747
  _globals['_EVENTTOKEN']._serialized_end=822
# @@protoc_insertion_point(module_scope)
