# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: weather_station.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "weather_station.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x15weather_station.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\ncore.proto"\x94\x02\n\x15VirtualWeatherStation\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nstation_id\x18\x02 \x01(\t\x12\x1c\n\tgeo_point\x18\x03 \x01(\x0b\x32\t.GeoPoint\x12\x13\n\x0blocation_id\x18\x04 \x01(\t\x12\x12\n\nhas_precip\x18\x05 \x01(\x08\x12(\n\x0bstationType\x18\x06 \x01(\x0e\x32\x13.WeatherStationType\x12+\n\x07\x63reated\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07updated\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08\x64istance\x18\t \x01(\x01"\xea\x01\n\x0eWeatherStation\x12\x12\n\nstation_id\x18\x01 \x01(\t\x12\x1c\n\tgeo_point\x18\x02 \x01(\x0b\x32\t.GeoPoint\x12\x0c\n\x04\x63ity\x18\x04 \x01(\t\x12\r\n\x05state\x18\x05 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x06 \x01(\t\x12\x12\n\nhas_precip\x18\x08 \x01(\x08\x12(\n\x0bstationType\x18\n \x01(\x0e\x32\x13.WeatherStationType\x12\x15\n\rmore_info_url\x18\x0b \x01(\t\x12\x10\n\x08\x64istance\x18\x0c \x01(\x01\x12\x11\n\televation\x18\r \x01(\x05*=\n\x12WeatherStationType\x12\x0c\n\x08NATIONAL\x10\x00\x12\x07\n\x03PWS\x10\x01\x12\x10\n\x0cWEATHER_FLOW\x10\x02\x42\x19\n\x15\x63om.rachio.api.deviceP\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "weather_station_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"\n\025com.rachio.api.deviceP\001"
    _globals["_WEATHERSTATIONTYPE"]._serialized_start = 586
    _globals["_WEATHERSTATIONTYPE"]._serialized_end = 647
    _globals["_VIRTUALWEATHERSTATION"]._serialized_start = 71
    _globals["_VIRTUALWEATHERSTATION"]._serialized_end = 347
    _globals["_WEATHERSTATION"]._serialized_start = 350
    _globals["_WEATHERSTATION"]._serialized_end = 584
# @@protoc_insertion_point(module_scope)
