# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: yard_like_mine.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "yard_like_mine.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14yard_like_mine.proto\x1a\x17schedule_criteria.proto\x1a\x1fgoogle/protobuf/timestamp.proto"\xfd\x01\n\x0cYardLikeMine\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x1c\n\x10primary_photo_id\x18\x02 \x01(\tB\x02\x18\x01\x12\x1d\n\x15\x64istance_from_my_yard\x18\x03 \x01(\x05\x12\x13\n\x0bgreen_score\x18\x04 \x01(\x01\x12\x13\n\x0bwater_usage\x18\x05 \x01(\x01\x12\x0c\n\x04\x63ity\x18\x06 \x01(\t\x12\r\n\x05state\x18\x07 \x01(\t\x12\x15\n\rzone_photo_id\x18\x08 \x03(\t\x12+\n\x07updated\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nis_updated\x18\n \x01(\x08\x42\x19\n\x15\x63om.rachio.api.deviceP\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "yard_like_mine_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"\n\025com.rachio.api.deviceP\001"
    _globals["_YARDLIKEMINE"].fields_by_name["primary_photo_id"]._loaded_options = None
    _globals["_YARDLIKEMINE"].fields_by_name[
        "primary_photo_id"
    ]._serialized_options = b"\030\001"
    _globals["_YARDLIKEMINE"]._serialized_start = 83
    _globals["_YARDLIKEMINE"]._serialized_end = 336
# @@protoc_insertion_point(module_scope)
