#!/usr/bin/env bash
# Regenerate the committed Python proto stubs in src/rachio_mcp/proto/ from
# the reverse-engineered .proto sources in reverse-engineering/protos/.
#
# We ship pre-compiled stubs so runtime does not need protoc. Re-run this
# script when the Android APK's proto surface changes (rare) or when the
# tool set grows to need more messages.
#
# We compute the transitive closure of proto files starting from a small
# set of "seed" top-level services. That way the script keeps working even
# as Rachio add/remove imports in the source protos.
#
# Usage:
#   scripts/build_protos.sh
#   scripts/build_protos.sh /path/to/reverse-engineering

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RE_ROOT="${1:-$HERE/reverse-engineering}"
PROTO_IN="$RE_ROOT/protos"
PROTO_OUT="$HERE/src/rachio_mcp/proto"

if [[ ! -d "$PROTO_IN" ]]; then
  echo "ERROR: proto source directory not found: $PROTO_IN" >&2
  echo "Pass the reverse-engineering directory path as arg 1." >&2
  exit 1
fi

# Seeds are the top-level services our MCP tools call into. Their transitive
# closure is computed below — we don't need to hand-maintain every dep.
SEEDS=(
  schedule_service
  device_service
  location_service
)

cd "$HERE"

# Transitive closure using a tiny Python helper.
mapfile -t CLOSURE < <(uv run python - "$PROTO_IN" "${SEEDS[@]}" <<'PY'
import re, sys
from pathlib import Path

proto_dir = Path(sys.argv[1])
seeds = sys.argv[2:]

def deps(name: str) -> list[str]:
    path = proto_dir / f"{name}.proto"
    if not path.exists():
        return []
    out = []
    for line in path.read_text().splitlines():
        m = re.match(r'\s*import\s+"([^"]+)"', line)
        if not m:
            continue
        imp = m.group(1)
        if imp.startswith("google/"):
            continue
        out.append(imp.removesuffix(".proto"))
    return out

seen: set[str] = set()
stack = list(seeds)
while stack:
    name = stack.pop()
    if name in seen:
        continue
    seen.add(name)
    for d in deps(name):
        if d not in seen:
            stack.append(d)

for name in sorted(seen):
    print(name)
PY
)

echo "→ regenerating stubs from ${#CLOSURE[@]} proto files to $PROTO_OUT"
rm -rf "$PROTO_OUT"
mkdir -p "$PROTO_OUT"

PROTO_FILES=()
for name in "${CLOSURE[@]}"; do
  path="$PROTO_IN/${name}.proto"
  if [[ ! -f "$path" ]]; then
    echo "ERROR: missing proto file: $path" >&2
    exit 1
  fi
  PROTO_FILES+=("$path")
done

uv run python -m grpc_tools.protoc \
  -I"$PROTO_IN" \
  --python_out="$PROTO_OUT" \
  --grpc_python_out="$PROTO_OUT" \
  --pyi_out="$PROTO_OUT" \
  "${PROTO_FILES[@]}" 2>&1 | (grep -v "warning.*unused" || true)

# Drop an __init__.py so Python recognises it as a package.
cat >"$PROTO_OUT/__init__.py" <<'EOF'
"""Pre-compiled protobuf stubs for the Rachio mobile gRPC API.

Generated by scripts/build_protos.sh from reverse-engineering/protos/.
Do not edit by hand; changes will be overwritten on the next regen.

The generated modules use bare imports of the form `import foo_pb2` which
assume this directory is on sys.path. rachio_mcp.client adds it at import
time so consumers don't need to do anything.
"""
EOF

count=$(ls -1 "$PROTO_OUT"/*_pb2.py | wc -l | tr -d ' ')
echo "✓ wrote $count _pb2.py files to $PROTO_OUT"
